\LoadClass[a4paper,12pt]{article}
\usepackage[utf8x]{inputenc}
\usepackage{amsmath} % Mathematische Symbole
\usepackage{amssymb} % Mathematische Symbole
\usepackage{graphicx} % Bilder einfügen
\usepackage{wrapfig}
\usepackage{caption}
\usepackage{enumitem}
\usepackage[UKenglish]{babel}
\usepackage{float}
\usepackage{subcaption}
\usepackage{tabularx}
\usepackage{algorithm2e}
\usepackage{setspace}
\usepackage{fixltx2e}
\usepackage{lipsum}
\usepackage{multirow}
\usepackage{listings}
\usepackage{color}


% define colors for listings and not only
\definecolor{codegreen}{rgb}{0,0.6,0}
\definecolor{codegray}{rgb}{0.5,0.5,0.5}
\definecolor{codepurple}{rgb}{0.58,0,0.82}
\definecolor{backcolour}{rgb}{0.95,0.95,0.92}
\definecolor{reddish}{rgb}{0.8, 0.109, 0.109}

 % define listings style
\lstdefinestyle{mystyle}{
    backgroundcolor=\color{backcolour},   
    commentstyle=\color{codegreen},
    keywordstyle=\color{magenta},
    numberstyle=\tiny\color{reddish},
    stringstyle=\color{codepurple},
    basicstyle=\footnotesize\ttfamily,
    breakatwhitespace=false,         
    breaklines=trues,                 
    captionpos=b,                    
    keepspaces=true,                 
    numbers=left,                    
    numbersep=5pt,                  
    showspaces=false,                
    showstringspaces=false,
    showtabs=false,                  
    tabsize=2
}

\lstset{style=mystyle}
\lstset{aboveskip=3ex,belowskip=3ex}